- title: Produto exemplo
  ref: 00009999000
  url: exemplo.html
  category: Acessórios
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sequi ea sint iusto quibusdam dolor nisi autem qui dolores nam quis facilis pariatur, veniam ratione. Incidunt consectetur ducimus quisquam deleniti?
  images:
    - description: exemplo
      img_path: produt-exemplo.jpg
      
    - description: exemplo
      img_path: produt-exemplo.jpg

- title: Produto exemplo 2
  ref: 000099990002
  url: exemplo2.html
  category: Acessórios
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sequi ea sint iusto quibusdam dolor nisi autem qui dolores nam quis facilis pariatur, veniam ratione. Incidunt consectetur ducimus quisquam deleniti?
  images:
    - description: exemplo
      img_path: produt-exemplo.jpg

    - description: exemplo
      img_path: produt-exemplo.jpg
